#!/bin/sh
# Copyright (C) 2011 O.S. Systems Software LTDA.
# Licensed on MIT

finish_enabled() {
    return 0
}

finish_run() {
    if [ -n "$ROOTFS_DIR" ]; then
        if [ -n "$bootparam_rootdelay" ]; then
            debug "Sleeping for $rootdelay second(s) to wait root to settle..."
            sleep $bootparam_rootdelay
        fi

        if [ ! -d $ROOTFS_DIR/dev ]; then
            fatal "ERROR: There's no '/dev' on rootfs."
        fi

        info "Switching root to '$ROOTFS_DIR'..."

        debug "Moving /dev, /proc and /sys onto rootfs..."
        mount --move /dev $ROOTFS_DIR/dev
        if [ $? != 0 ]; then
            fatal "ERROR: mount --move /dev failed"
        fi
        mount --move /proc $ROOTFS_DIR/proc
        if [ $? != 0 ]; then
            fatal "ERROR: mount --move /proc failed"
        fi
        mount --move /sys $ROOTFS_DIR/sys
        if [ $? != 0 ]; then
            fatal "ERROR: mount --move /sys failed"
        fi

        cd $ROOTFS_DIR
        if [ $? != 0 ]; then
            fatal "ERROR: cd $ROOTFS_DIR failed"
        fi
        exec /sbin/switch_root -c /dev/console $ROOTFS_DIR ${bootparam_init:-/sbin/init} $bootparam_runlevel
        if [ $? != 0 ]; then
            fatal "ERROR: switch_root failed"
        fi
    else
        debug "No rootfs has been set"
    fi
}
