#!/bin/sh
# Copyright (C) 2011, 2017 O.S. Systems Software LTDA.
# Licensed on MIT

mdev_enabled() {
    if [ ! -e /sbin/mdev ]; then
        debug "/sbin/mdev doesn't exist"
        return 1
    fi

    return 0
}

mdev_run() {
    mkdir -m 1777 /dev/shm

    mkdir -m 0755 /dev/pts
    mount -t devpts devpts /dev/pts
    if [ $? != 0 ]; then
        fatal "ERROR: Could not mount /dev/pts"
    fi

    echo /sbin/mdev > /proc/sys/kernel/hotplug
    /sbin/mdev -s
    if [ $? != 0 ]; then
        fatal "ERROR: mdev failed"
    fi
}
